import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBarHead from "../app/component/NavigationBar/NavBarHead";
import NavBarBody from "../app/component/NavigationBar//NavBarBody";
import NavBarEnd from "../app/component/NavigationBar//NavBarEnd";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Computer Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* className={`${geistSans.variable} ${geistMono.variable}`} */}
      <body>
        <div className="wrapper">
        <div className="item">
        <NavBarHead />
        <NavBarBody />
        <NavBarEnd />
      </div>
          {children}
          <div className="footer">
            <span>
              <p>This Project Done by Group 05.</p>
            </span>
          </div>
        </div>
      </body>
    </html>
  );
}
